services:
  internalsystem:
    build:
      context: .
      dockerfile: src/Pixelz.InternalSystem/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventStoreDb__ConnectionString=esdb://eventstore:2113?tls=false
    depends_on:
      - eventstore
    networks:
      - pixelz-network
      
  checkoutservice:
    build:
      context: .
      dockerfile: src/Pixelz.OrderService/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EventStoreDb__ConnectionString=esdb://eventstore:2113?tls=false
    depends_on:
      - eventstore
    networks:
      - pixelz-network

  eventstore:
    image: eventstore/eventstore:23.10.0-jammy
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - eventstore-data:/var/lib/eventstore
    networks:
      - pixelz-network

networks:
  pixelz-network:
    driver: bridge

volumes:
  eventstore-data: